---
title: "Get MECS Coeffs"
author: "Jaxon Stuhr"
date: "2/9/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
library(tidyverse)
library(readxl)
library(janitor)
library(writexl)
```

```{r}
# unit conversions
kwh_to_btu = 3412.1416
mil_kwh_to_tbtu = kwh_to_btu * (10^6) / (10^12)
```

```{r}
# read in raw mecs tables
raw3_5 = read_excel(here("data", "Table3_5.xlsx")) # UNITS = Tbtu
raw3_6 = read_excel(here("data", "Table3_6.xlsx")) # UNITS = Tbtu
raw7_7 = read_excel(here("data", "Table7_7.xlsx")) # UNITS = varied, million kWh or billion cu ft or billion btu
raw11_1 = read_excel(here("data", "Table11_1.xlsx")) # UNITS = million kWh
raw11_3 = read_excel(here("data", "Table11_3.xlsx")) # UNITS = million kWH (?)
raw11_5 = read_excel(here("data", "Table11_5.xlsx")) # UNITS = million kWh
```

```{r}
# clean table 3.5
# Total united states only
mecs3_5 = raw3_5 %>% 
  # delete top rows
  tail(-12) %>% 
  # rename cols
  rename("naics_code" = "Released: February 2021",
         "selected_byproducts_in_fuel_consumption_total" = "...3",
         "blast_furnace_coke_oven_gases" = "...4",
         "waste_gas" = "...5",
         "petroleum_coke" = "...6",
         "pulping_liquor_or_black_liquor" = "...7",
         "wood_chips_bark" = "...8",
         "waste_oils_tars_waste_minerals" = "...9") %>%
  # remove subsector description column
  select(naics_code, selected_byproducts_in_fuel_consumption_total : waste_oils_tars_waste_minerals) %>%
  # remove blank rows
  remove_empty("rows") %>% 
  head(82)
```

```{r}
# clean table 3.6
# Total united states only
mecs3_6 = raw3_6 %>% 
  # delete top rows
  tail(-17) %>% 
  # rename cols
  rename("naics_code" = "Released: February 2021",
         "pulping_liquor_or_black_liquor" = "...3",
         "biomass_total" = "...4",
         "agricultural_waste" = "...5",
         "wood_harvested_directly_from_trees" = "...6",
         "wood_residues_byproducts_from_mill_processing" = "...7",
         "wood_related_paper_related_refuse" = "...8") %>%
  # remove subsector description column
  select(naics_code, pulping_liquor_or_black_liquor : wood_related_paper_related_refuse) %>%
  # remove blank rows
  remove_empty("rows") %>% 
  head(14)
```

```{r}
# clean table 7.7
# Total united states only
mecs7_7 = raw7_7 %>% 
  # delete top rows
  tail(-16) %>% 
  # rename cols
  rename("naics_code" = "Released: September 2021",
         "elec_tot_mil_kwh" = "...3",
         "elec_loc_utility_mil_kwh" = "...4",
         "elec_other_sources_mil_kwh" = "...5",
         "ng_tot_bil_cu_ft" = "...6",
         "ng_loc_utility_bil_cu_ft" = "...7",
         "ng_other_sources_bil_cu_ft" = "...8",
         "steam_tot_bil_btu" = "...9",
         "steam_loc_utility_bil_btu" = "...10",
         "steam_other_sources_bil_btu" = "...11") %>%
  # remove subsector description column
  select(naics_code, elec_tot_mil_kwh : steam_other_sources_bil_btu) %>%
  # remove blank rows
  remove_empty("rows") %>% 
  head(82)
```
