---
title: "MECS Electricity, Steam, and Natural Gas Sources"
author: "Jaxon Stuhr"
date: "5/21/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
library(here)
library(tidyverse)
library(readxl)
library(janitor)
library(writexl)
```

```{r}
# unit conversions
kwh_to_btu = 3412.1416
mil_kwh_to_tbtu = kwh_to_btu * (10^6) / (10^12)
ng_bil_cu_ft_to_tbtu = 1.0388 # calculate from mecs tables 5.3, 5.4
bil_btu_to_tbtu = 0.001
```

```{r}
raw7_7 = read_excel(here("data", "Table7_7.xlsx")) # UNITS = varied, million kWh or billion cu ft or billion btu
raw11_1 = read_excel(here("data", "Table11_1.xlsx")) # UNITS = million kWh
raw11_3 = read_excel(here("data", "Table11_3.xlsx")) # UNITS = million kWH (?)
raw11_5 = read_excel(here("data", "Table11_5.xlsx")) # UNITS = million kWh
```

```{r}
# clean table 7.7
# Total united states only
mecs7_7 = raw7_7 %>% 
  # delete top rows
  tail(-16) %>% 
  # rename cols
  rename("naics_code" = "Released: September 2021",
         "elec_tot_mil_kwh" = "...3",
         "elec_loc_utility_mil_kwh" = "...4",
         "elec_other_sources_mil_kwh" = "...5",
         "ng_tot_bil_cu_ft" = "...6",
         "ng_loc_utility_bil_cu_ft" = "...7",
         "ng_other_sources_bil_cu_ft" = "...8",
         "steam_tot_bil_btu" = "...9",
         "steam_loc_utility_bil_btu" = "...10",
         "steam_other_sources_bil_btu" = "...11") %>%
  # remove subsector description column
  select(naics_code, elec_tot_mil_kwh : steam_other_sources_bil_btu) %>%
  # remove blank rows
  remove_empty("rows") %>% 
  # total US only
  head(82) %>% 
  # convert values to numeric
  mutate_all(as.numeric) %>% 
  # update electricity units to tbtu
  mutate_at(vars(elec_tot_mil_kwh:elec_other_sources_mil_kwh),
            .funs = funs(. * mil_kwh_to_tbtu)) %>%
  # update ng units to tbtu
  mutate_at(vars(ng_tot_bil_cu_ft:ng_other_sources_bil_cu_ft),
            .funs = funs(. * ng_bil_cu_ft_to_tbtu)) %>%
  # update steam units to tbtu
  mutate_at(vars(steam_tot_bil_btu:steam_other_sources_bil_btu),
            .funs = funs(. * bil_btu_to_tbtu)) %>% 
  mutate_all(round)
```

```{r}
# clean table 11.1
# Total united states only
mecs11_1 = raw11_1 %>% 
  # delete top rows
  tail(-11) %>% 
  # rename cols
  rename("naics_code" = "Released: February 2021",
         "elec_purchases" = "...3",
         "elec_transfers_in" = "...4",
         "elec_total_onsite_generation" = "...5",
         "elec_sales_and_transfers_offsite" = "...6",
         "elec_net_demand_for_electricity" = "...7") %>%
  # remove subsector description column
  select(naics_code, elec_purchases : elec_net_demand_for_electricity) %>%
  # remove blank rows
  remove_empty("rows") %>%
  # total US only
  head(82) %>% 
  # convert values to numeric
  mutate_all(as.numeric) %>% 
  # convert all values from million kWh to TBtu
  mutate_at(vars(elec_purchases:elec_net_demand_for_electricity),
            .funs = funs(. * mil_kwh_to_tbtu)) %>% 
  mutate_all(round)
```

```{r}
# clean table 11.3
# Total united states only
mecs11_3 = raw11_3 %>% 
  # delete top rows
  tail(-12) %>% 
  # rename cols, drop onsite generation bc included in 11.1
  rename("naics_code" = "Released: February 2021",
         "elec_cogeneration" = "...4",
         "elec_renewable_energy_excluding_wood_and_biomass" = "...5",
         "elec_other" = "...6") %>%
  # remove subsector description column
  select(naics_code, elec_cogeneration : elec_other) %>%
  # remove blank rows
  remove_empty("rows") %>% 
  # total US only
  head(82) %>% 
  # convert values to numeric
  mutate_all(as.numeric) %>% 
  # convert all values from million kWh to TBtu
  mutate_at(vars(elec_cogeneration : elec_other),
            .funs = funs(. * mil_kwh_to_tbtu)) %>% 
  mutate_all(round)
```

```{r}
# clean table 11.3
# Total united states only
mecs11_5 = raw11_5 %>% 
  # delete top rows
  tail(-12) %>% 
  # rename cols
  rename("naics_code" = "Released: February 2021",
         "elec_totals_sales_transfers_offsite" = "...3",
         "elec_utility_purchaser" = "...4",
         "elec_nonutility_purchaser" = "...5") %>%
  # remove subsector description column
  select(naics_code, elec_totals_sales_transfers_offsite : elec_nonutility_purchaser) %>%
  # remove blank rows
  remove_empty("rows") %>% 
  # total US only
  head(82)  %>% 
  # convert values to numeric
  mutate_all(as.numeric) %>% 
  # convert all values from million kWh to TBtu
  mutate_at(vars(elec_totals_sales_transfers_offsite:elec_nonutility_purchaser),
            .funs = funs(. * mil_kwh_to_tbtu)) %>% 
  mutate_all(round)
```

```{r}
# merge all tables by naics code
mecs_elec_ng_steam = mecs7_7 %>% 
  merge(mecs11_1, by = "naics_code", all = TRUE, sort = FALSE) %>% 
  merge(mecs11_3, by = "naics_code", all = TRUE, sort = FALSE) %>% 
  merge(mecs11_5, by = "naics_code", all = TRUE, sort = FALSE) %>% 
  mutate_all(funs(ifelse(is.na(.), 0, .))) # set all NAs to zero
```

Add in rows for end-uses of MECS 5.4, as 3.5 and 3.6 only have sector-level data. This code loops through each NAICS code, adding 15 new rows after each "Total" row for each end use. These values are left blank for now and are filled in in Excel. 
```{r}
mecs_elec_ng_steam = mecs_elec_ng_steam %>% 
  mutate(end_use = "TOTAL FUEL CONSUMPTION", .after = naics_code)
end_uses = unique(mecs5_4$end_use)
naics_codes = unique(mecs_elec_ng_steam$naics_code)
row = 1
for (code in naics_codes) {
  mecs_elec_ng_steam = mecs_elec_ng_steam %>% 
    add_row(naics_code = code, end_use = "Conventional Boiler Use", .after = row) %>% 
    add_row(naics_code = code, end_use = "CHP and/or Cogeneration Process", .after = row+1) %>% 
    add_row(naics_code = code, end_use = "Process Heating", .after = row+2) %>% 
    add_row(naics_code = code, end_use = "Process Cooling and Refrigeration", .after = row+3) %>% 
    add_row(naics_code = code, end_use = "Machine Drive", .after = row+4) %>% 
    add_row(naics_code = code, end_use = "Electro-Chemical Processes", .after = row+5) %>% 
    add_row(naics_code = code, end_use = "Other Process Use", .after = row+6) %>% 
    add_row(naics_code = code, end_use = "Facility HVAC (f)", .after = row+7) %>% 
    add_row(naics_code = code, end_use = "Facility Lighting", .after = row+8) %>% 
    add_row(naics_code = code, end_use = "Other Facility Support", .after = row+9) %>% 
    add_row(naics_code = code, end_use = "Onsite Transportation", .after = row+10) %>% 
    add_row(naics_code = code, end_use = "Conventional Electricity Generation", .after = row+11) %>% 
    add_row(naics_code = code, end_use = "Other Nonprocess Use", .after = row+12) %>% 
    add_row(naics_code = code, end_use = "End Use Not Reported", .after = row+13) 
  row = row + 15 #length(end_uses)
}
```

Write to excel file
```{r}
write_xlsx(mecs_elec_ng_steam, here("outputs", "MECS_Elec_NG_Steam_Clean.xlsx"))
```