---
title: "Build Final Dataframe"
author: "Jaxon Stuhr"
date: "2/10/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
library(tidyverse)
```

```{r}
# add end uses and blank rows to coeffs_wrangled
full_coeffs = coeffs_wrangled %>% 
  mutate(end_use = "TOTAL FUEL CONSUMPTION", .after = naics_code)
end_uses = unique(mecs5_4_wrangled$end_use)
naics_codes = unique(coeffs_wrangled$naics_code)
row = 1
for (code in naics_codes) {
  full_coeffs = full_coeffs %>% 
    add_row(naics_code = code, end_use = "Conventional Boiler Use", .after = row) %>% 
    add_row(naics_code = code, end_use = "CHP and/or Cogeneration Process", .after = row+1) %>% 
    add_row(naics_code = code, end_use = "Process Heating", .after = row+2) %>% 
    add_row(naics_code = code, end_use = "Process Cooling and Refrigeration", .after = row+3) %>% 
    add_row(naics_code = code, end_use = "Machine Drive", .after = row+4) %>% 
    add_row(naics_code = code, end_use = "Electro-Chemical Processes", .after = row+5) %>% 
    add_row(naics_code = code, end_use = "Other Process Use", .after = row+6) %>% 
    add_row(naics_code = code, end_use = "Facility HVAC (f)", .after = row+7) %>% 
    add_row(naics_code = code, end_use = "Facility Lighting", .after = row+8) %>% 
    add_row(naics_code = code, end_use = "Other Facility Support", .after = row+9) %>% 
    add_row(naics_code = code, end_use = "Onsite Transportation", .after = row+10) %>% 
    add_row(naics_code = code, end_use = "Conventional Electricity Generation", .after = row+11) %>% 
    add_row(naics_code = code, end_use = "Other Nonprocess Use", .after = row+12) %>% 
    add_row(naics_code = code, end_use = "End Use Not Reported", .after = row+13) 
  row = row + 14 #length(end_uses)
}
```

