---
title: "Data Wranglin"
author: "Jaxon Stuhr"
date: "1/27/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
library(tidyverse)
library(readxl)
library(janitor)
```

```{r}
# read in data 
mecs5_2_raw = read_excel(here("data", "MECS_Table_5_2.xlsx"))

mecs5_2 = mecs5_2_raw %>% 
  # delete top rows
  tail(-13) %>% 
  # rename cols
  rename("naics_code" = "Released: February 2021",
         "end_use" = "...2",
         "total" = "...3",
         "net_electricity" = "...4",
         "residual_fuel_oil" = "...5",
         "distillate_fuel_oil_and_diesel_fuel" = "...6",
         "nat_gas" = "...7",
         "hgl_excluding_ng" = "...8",
         "coal_excluding_coke_and_breeze" = "...9",
         "other" = "...10") %>%
  # remove blank rows
  remove_empty("rows") 
```

```{r}
# set NAICS code vals for all entries with blank codes
counter = 1
for (entry in mecs5_2$naics_code) {
  if (is.na(entry)) {
    mecs5_2$naics_code[counter] = mecs5_2$naics_code[counter - 1]
  }
  counter = counter + 1
}  
```

```{r}
# update all non-numeral values in mecs table
```


```{r}
# convert data type to numeric for columns 3 - 10
cols_to_numeric <- c(3:10) 
mecs5_2[ , cols_to_numeric] = apply(mecs5_2[ , cols_to_numeric], 2,            # Specify own function within apply
                    function(x) as.numeric(as.character(x)
                                           )
                    )
```


```{#r}
# remove subtotal and total rows 
mecs5_2 = mecs5_2 %>% 
  filter(!(end_use %in% c("Indirect Uses-Boiler Fuel", 
                          "Direct Uses-Total Process", 
                          "Direct Uses-Total Nonprocess",
                          "TOTAL FUEL CONSUMPTION"))) %>% 
  na.omit()
```

```{#r}
# remove total rows in beginning (naics_code = 311-339)
mecs5_2 = mecs5_2 %>% 
  filter(naics_code != "311 - 339")
```

```{r}
update_naics_vals = function(new_vals, mecs_table, current_code, next_code, current_row, next_row, end_use_count, char_count) {
    # update values of usage columns when match is found (indices are for values that need updating)
    new_vals[3:10] = new_vals[3:10] - mecs_table[next_row, 3:10]
    # update next row (w same end use) and code
    next_row = next_row + end_use_count
    next_code = mecs_table$naics_code[next_row]
    # check if next naics code is also sub-code of current code
    if (
      nchar(current_code) == char_count & 
      nchar(next_code) > char_count & 
      substr(next_code, 1, char_count) == current_code
      ) {
      # if yes, recall update naics function
        return(update_naics_vals(new_vals, mecs_table, current_code, next_code, current_row, next_row, end_use_count, char_count))
    } else {
      # if no, return new vals
        return(new_vals)
      }
   # update_naics_vals(new_vals, mecs_table, current_code, next_code, current_row, next_row, end_use_count, char_count)
  #}
}
```

## Update 4-digit NAICS Codes

```{r}
# initialize new table
new_mecs_table = mecs5_2[0, ]
# count number of end uses /// number each time each naics code appears
end_use_count = sum(mecs5_2$naics_code == mecs5_2$naics_code[1])
char_count = 4 # updating 4 digit naics codes
# iterate through rows in mecs table
for (row in 1: (nrow(mecs5_2) - end_use_count) ) {
  # define current code, next code, and next row index with same end use as current
  current_code = mecs5_2$naics_code[row]
  next_row = row + end_use_count
  next_code = mecs5_2$naics_code[next_row]
  # build array of vals for row to be updated
  new_vals = mecs5_2[row, ]
  # check next row is subcode of current code
  if (
      nchar(current_code) == char_count & 
      nchar(next_code) > char_count & 
      substr(next_code, 1, char_count) == current_code
      ) {
    # if yes, update vals
          new_mecs_table[nrow(new_mecs_table) + 1,] = 
    update_naics_vals(new_vals, mecs5_2, current_code, next_code, current_row, next_row, end_use_count, char_count)
  } else {
    # if not, append row to data
    new_mecs_table[nrow(new_mecs_table) + 1,] = new_vals
  }
}
```

```{r}
# add last naics code values on to new data frame
end_of_old_table = mecs5_2[as.numeric(count(mecs5_2) - end_use_count + 1):as.numeric(count(mecs5_2)), ]
new_mecs_table = rbind(new_mecs_table, end_of_old_table)
```

## Update 3-digit NAICS Codes

```{r}
# initialize new table
final_mecs_table = new_mecs_table[0, ]
# count number of end uses /// number each time each naics code appears
end_use_count = sum(new_mecs_table$naics_code == new_mecs_table$naics_code[1])
char_count = 3 # updating 4 digit naics codes
# iterate through rows in mecs table
for (row in 1:(nrow(new_mecs_table) - end_use_count) ) {
  # define current code, next code, and next row index with same end use as current
  current_code = new_mecs_table$naics_code[row]
  next_row = row + end_use_count
  next_code = new_mecs_table$naics_code[next_row]
  # build array of vals for row to be updated
  new_vals = new_mecs_table[row, ]
  # check next row is subcode of current code
  if (
      nchar(current_code) == char_count & 
      nchar(next_code) > char_count & 
      substr(next_code, 1, char_count) == current_code
      ) {
    # if yes, update vals
          final_mecs_table[nrow(final_mecs_table) + 1,] = 
    update_naics_vals(new_vals, new_mecs_table, current_code, next_code, current_row, next_row, end_use_count, char_count)
  } else {
    # if not, append row to data
    final_mecs_table[nrow(final_mecs_table) + 1,] = new_vals
  }
}
```

```{r}
# add last naics code values on to new data frame
end_of_old_table = new_mecs_table[as.numeric(count(new_mecs_table) - end_use_count + 1):as.numeric(count(new_mecs_table)), ]
final_mecs_table = rbind(final_mecs_table, end_of_old_table)
```

